steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/your-image',
        '.',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}',
        '--build-arg', 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}',
        '--build-arg', 'NEXT_PUBLIC_API_URL=${_API_URL}'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-image']
images:
  - 'gcr.io/$PROJECT_ID/your-image'
